### PR TITLE
Use $this in return phpdoc when appropriate

### PR DESCRIPTION
**Pull request by iansltx**
This allows for proper typehint recognition/code completion for classes extending Pdf and Image.

### CODE REVIEW

**Comment by mikehaertl** [comment]
Hmm. I'm not sure if there's a standard for this. I've also seen some using the type `static` in this case. I think, it also depends on the IDE you use and how code completion is implemented there, right?

Do you maybe have some pointers with further documentation?

**Comment by iansltx** [comment]
This patch works with PHPStorm. My guess is that static would work as well for Storm; will see if phpdoc has a recommendation one way or another.

**Comment by mikehaertl** [comment]
I'd prefer `static`, because I've seen that in some frameworks. If you agree and change it, I'll merge it.

**Comment by iansltx** [comment]
Changed.

**Comment by mikehaertl** [comment]
Thanks!

**Pull request merged**
