### PR TITLE
Add Dev Dependency on phpunit 6

### LINKED ISSUE #337: phpunit/phpunit needs to be a dev dependency
`phpunit/phpunit` should really be a dev dependency in `composer.json`. This way when trying to run the phpunit tests we can easily install the correct version.

For example, if you just try and use the latest phpunit you get the following error:
```
PHPUnit 8.5.1 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 13:
  - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.

  Test results may not be as expected.
```

### PR DESCRIPTION
**Pull request by timwsuqld**
Fix #337

### CODE REVIEW

**Comment by timwsuqld** [comment]
I've rebased now that the build has been fixed. Travis highlights that at least for dev requirements, we now need at least PHP 7. I'm not sure if that's a bad thing at this stage for new releases, given that even 7.1 is EOL now.

**Comment by mikehaertl** [comment]
Hmm, can't we use a 5.x version of phpunit just as it was before? I'm not happy to drop support for older PHP versions just because of the test setup. There may still be devs out there with weird restrictions that require PHP 5.x and the library itself runs fine with it.

**Comment by mikehaertl** [comment]
For comparison I had a look at yii2-apidoc where they also support PHP 5.4 - 7.3. Their main trick seems to be that they use `<7` as version constraint for phpunit. Seems like composer then picks the latest supported version depending on PHP version. Maybe we should try this, too? Their travis setup also looks interesting.

See here:
* https://github.com/yiisoft/yii2-apidoc/blob/7f08120da99437a99d33c447f64a8b2675009d44/composer.json#L34
* https://github.com/yiisoft/yii2-apidoc/blob/7f08120da99437a99d33c447f64a8b2675009d44/.travis.yml

**Comment by timwsuqld** [comment]
I assumed due to the commit message on 1c1e6fb6efabfd0635f7906e3c20eb88335a6433 that you'd made changes that weren't backwards compatible with PHPUnit 5 (I know on a work project were we'd had issues when we upgraded PHP Unit). It does appear you've made it backwards compatible, and it looks like it should work with PHPUnit 5, 6 and 7. I've updated the branch to attempt to use a range of phpunit versions, without moving to PHPUnit 8 which breaks things.

**Pull request merged**
