### PR TITLE
Added expression for XML (svg) detection

### PR DESCRIPTION
**Pull request by PBXg33k**
Simple addition to the code to accept XML strings as input.
This adds the option to generate PDF documents from a SVG (vector)

### CODE REVIEW

**Comment by mikehaertl** [comment]
Hmm, can you give me a use case, where you would add a page or cover from a XML file?

**Comment by PBXg33k** [comment]
We use it in a project which consists of an API server which generates parcel labels from a SVG source file.

In our case we have one or multiple SVG templates, depending on various conditions.
Based on the arguments passed by the user a SVG string is generated which represents the parcel label which is to be generated, this string is passed to the library and the PDF output is returned back to the user.

**Comment by mikehaertl** [comment]
Ok, sounds reasonable. I just want to avoid having detectors for all kinds of text formats. This would be out of the scope of this project. But I'm fine with this. 

Do you think you could also provide a test case for this? See here:
https://github.com/mikehaertl/phpwkhtmltopdf/blob/master/tests/PdfTest.php#L24

This test is not perfect, but at least it makes sure, that nothing breaks.

**Comment by PBXg33k** [comment]
I will add a test case in the next few hours and update the PR.

**Comment by mikehaertl** [comment]
Cool, you just have to push another commit, it will update the PR automatically.

**Comment by mikehaertl** [comment]
Thanks!

**Pull request merged**
